_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: en-gb
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  age_field_formatter: 0
  announcements_feed: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor5: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_checkout_order_fields: 0
  commerce_log: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  commerce_user_roles: 0
  config: 0
  consumers: 0
  contact: 0
  contextual: 0
  crop: 0
  datetime: 0
  dblog: 0
  decoupled_router: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  image_effects: 0
  image_widget_crop: 0
  inline_entity_form: 0
  language: 0
  link: 0
  locale: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_per_role: 0
  menu_ui: 0
  message: 0
  message_notify: 0
  mysql: 0
  next: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  private_message: 0
  private_message_notify: 0
  profile: 0
  redirect_after_login: 0
  role_theme_switcher: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  smtp: 0
  state_machine: 0
  subrequests: 0
  system: 0
  taxonomy: 0
  taxonomy_import: 0
  taxonomy_vocab_build: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  claro: 0
  gin: 0
  kinkforme: 0
profile: standard
