<?php

/**
 * Implements hook_uninstall().
 */
function commerce_marketplace_uninstall() {
  // Load the role entity.
  $role = \Drupal\user\Entity\Role::load('commerce_marketplace_store_owner');

  // Check if the role exists.
  if ($role) {
    // Delete the role.
    $role->delete();
    \Drupal::logger('commerce_marketplace')->notice('The role commerce_marketplace_store_owner has been deleted.');
  }
}
