name: kinkforme
type: drupal10
docroot: web
php_version: "8.2"
composer_version: "2"
nodejs_version: "16"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
web_environment: []
router_http_port: "80"
router_https_port: "443"

use_mailhog: true

disable_settings_management: true

hooks:
  post-start:
    - exec-host: bash .ddev/scripts/generate-certificates.sh
    # - exec: cd /var/www/html/next_commerce_api && npm install
    # - exec: cd /var/www/html/next_commerce_api && pm2 start "npm run dev"
