name: Build & lint project
on: [push]
env:
  PHP_VERSION: '8.2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run Drupal tests
        run: |
          # Run Drupal core tests
          vendor/bin/phpunit -c web/core web/core/tests

          # Run contributed module tests (replace "contrib" with the actual path to your contributed modules)
          vendor/bin/phpunit -c web/core web/modules/contrib

          # Run custom module tests (replace "custom" with the actual path to your custom modules)
          vendor/bin/phpunit -c web/core web/modules/custom
