name: Build & Lint Project

on: [push]

env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install PHP dependencies
        run: composer install --prefer-dist

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js dependencies
        run: |
          cd react-app
          npm install

      - name: Build React application
        run: |
          cd react-app
          npm run build

      # Optional: Lint React application
      # - name: Lint React application
      #   run: |
      #     cd react-app
      #     npm run lint
