name: Build & Lint Project

on: [push]

env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '16'
  NEXT_JS_APP_PATH: 'next_commerce_api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install PHP dependencies
        run: composer install --prefer-dist

      - name: Remove .ddev directory
        run: rm -rf .ddev

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js dependencies
        run: |
          cd ${{ env.NEXT_JS_APP_PATH }}
          npm install

      - name: Build Vue.js application
        run: |
          cd ${{ env.NEXT_JS_APP_PATH }}
          npm run build

      # Optional: Lint Vue.js application
      # - name: Lint Vue.js application
      #   run: |
      #     cd next_commerce_api
      #     npm run lint
