name: Deploy to Digital Ocean droplet
on:
  workflow_run:
    workflows: ["Build & lint project"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy and install dependencies
      - name: Deploy to droplet using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          env:
            COMPOSER_ALLOW_SUPERUSER: 1
          script: |
            cd ${{ secrets.DOCROOT }}
            sudo git pull
            sudo composer install
            # Drupal-specific commands
            sudo ./vendor/bin/drush cr
            sudo ./vendor/bin/drush config:import -y
            sudo ./vendor/bin/drush import-all -y
            sudo ./vendor/bin/drush updatedb -y
            sudo ./vendor/bin/drush cr
            # Remove .ddev folder
            sudo rm -rf .ddev

      # Adjust ownership and permissions
      - name: Adjust ownership and permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data ${{ secrets.DOCROOT }}
            sudo chmod -R 755 ${{ secrets.DOCROOT }}
