name: Deploy to Digital Ocean Droplet

on:
  workflow_run:
    workflows: ["Build & Lint Project"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to droplet using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            # Navigate to the Drupal root directory
            cd ${{ secrets.DOCROOT }}
            git pull  # Pull latest changes

            # Rebuild Drupal environment
            rm -rf vendor
            composer install
            ./vendor/bin/drush cr
            ./vendor/bin/drush config:import -y
            ./vendor/bin/drush updatedb -y
            ./vendor/bin/drush cr

            # Update and build Vue.js application
            cd web/themes/custom/kinkforme
            npm install
            npm run build

      - name: Adjust ownership and permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data ${{ secrets.DOCROOT }}  # Correct file ownership
